### ISSUE TITLE
ent fails: Immutable undefined (type *edge.Descriptor has no field or method Immutable)

### ISSUE THREAD

**Issue by yonas** [mrusme/journalist#3]
```
$ make
fatal: No names found, cannot describe anything.
ent generate --feature sql/upsert ./ent/schema
entc/load: # command-line-arguments
.entc/entc_github.com_mrusme_journalist_ent_schema_1667657943.go:115:19: ed.Immutable undefined (type *edge.Descriptor has no field or method Immutable)

make: *** [Makefile:7: ent] Error 1
```

Ubuntu 22.10 amd64
go 1.19.2

**Comment by mrusme** [comment]
While I could not reporduce your issue I nevertheless updated the `Makefile` to call `go generate` instead of `ent` directly. Please make sure you followed the [set up instructions](https://entgo.io/docs/tutorial-setup) for ent and try again. Also make sure you did not unintentionally update go modules yourself.
